// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id string) error
	DropAllUsers(ctx context.Context) error
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id string) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UserExistsByEmail(ctx context.Context, email string) (int64, error)
}

var _ Querier = (*Queries)(nil)
